version: "3"
services: 
  proxy:
    build: 
      context: ./Proxy
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    restart: always
  client:
    build:
      context: ./Task19UI
      dockerfile: Dockerfile
    ports: 
      - "9000:80"
  api:
    build: 
      context: ./Task19API
      dockerfile: ./Task19API/Dockerfile
    ports: 
      - "5000:80"
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: 19task
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: